name: Django Tests and Generate Pydoc Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: my_site.settings
      run: |
        python manage.py migrate

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: my_site.settings
      run: |
        python manage.py test

    - name: Generate Pydoc HTML with script
      env:
        DJANGO_SETTINGS_MODULE: my_site.settings
      run: |
        mkdir -p docs
        python generate_docs.py