name: Generate Pydoc Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Pydoc HTML for models and views
      run: |
        mkdir -p docs
        python -m pydoc -w blog.models
        python -m pydoc -w blog.views
        mv blog.models.html docs/models.html
        mv blog.views.html docs/views.html

    - name: Commit generated docs
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add docs/
        git commit -m "Actualizar documentación Pydoc" || echo "No hay cambios que commitear"
        git push

