name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test

    - name: Generate Pydoc HTML
      run: |
        mkdir -p docs
        python -m pydoc -w blog.models
        python -m pydoc -w blog.views
        mv blog.models.html docs/models.html
        mv blog.views.html docs/views.html
  

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: pydoc-html
        path: docs/index.html
